[pytest]
#添加backend目录到python路径
pythonpath = .
#测试路径
testpaths = tests
#覆盖率配置
addopts =
    --cov=backend/app
    --cov-report=html
    --cov-report=term-missing
    --cov-branch
    --headed
    --alluredir=allure-results

asyncio_mode = auto
#忽略第三方库的警告
filterwarnings =
    ignore::DeprecationWarning:jose
    ignore::PendingDeprecationWarning:starlette